import type { Metadata } from 'next';
import local from 'next/font/local';
import './globals.css';
import { cn } from '@/lib/utils';

export const shabnam = local<'--font-shabnam'>({
    src: [
        { path: '../public/fonts/shabnam/Shabnam-FD-WOL.woff2', weight: '400' },
        {
            path: '../public/fonts/shabnam/Shabnam-Medium-FD-WOL.woff2',
            weight: '500',
        },
        {
            path: '../public/fonts/shabnam/Shabnam-Bold-FD-WOL.woff2',
            weight: '700',
        },
    ],
});

export const nunito = local<'--font-nunito'>({
    src: [
        { path: '../public/fonts/nunito/Nunito-Regular.ttf', weight: '400' },
        { path: '../public/fonts/nunito/Nunito-Medium.ttf', weight: '500' },
        { path: '../public/fonts/nunito/Nunito-SemiBold.ttf', weight: '600' },
        { path: '../public/fonts/nunito/Nunito-Bold.ttf', weight: '700' },
    ],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="fa-IR"
            dir="rtl"
            className={cn('font-sans',shabnam.className, "bg-background text-text-primary")}
        >
            <body>{children}</body>
        </html>
    );
}
