import type { Metadata, Viewport } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { cn } from '@/lib/utils';
import { TooltipProvider } from '@/components/ui/tooltip';
import { Toaster } from '@/components/ui/sonner';
import Providers from './providers';

const shabnam = localFont({
    src: [
        { path: '../public/fonts/shabnam/Shabnam-FD-WOL.woff2', weight: '400' },
        {
            path: '../public/fonts/shabnam/Shabnam-Medium-FD-WOL.woff2',
            weight: '500',
        },
        {
            path: '../public/fonts/shabnam/Shabnam-Bold-FD-WOL.woff2',
            weight: '700',
        },
    ],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export const viewport: Viewport = {
    userScalable: false,
    width: 'device-width',
    themeColor: '#000000'
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="fa-IR"
            dir="rtl"
            className={cn(
                'font-sans',
                shabnam.className,
                'bg-background text-text-primary',
            )}
        >
            <body>
                <Providers>
                    {children}
                </Providers>
            </body>
        </html>
    );
}
