// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv';
import { defineConfig, env } from 'prisma/config';

if (process.env.NODE_ENV === 'development') {
    config({ path: '.env.development' });
} else {
    config({ path: '.env' });
}

export default defineConfig({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'prisma/migrations/dev',
    },
    datasource: {
        url: env('DATABASE_URL'),
    },
});
